/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppApprovalsRouteImport } from './routes/_app/approvals'
import { Route as AppBrandRouteImport } from './routes/_app/brand'
import { Route as AppCampaignsRouteImport } from './routes/_app/campaigns'
import { Route as AppMapRouteImport } from './routes/_app/map'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSourcesRouteImport } from './routes/_app/sources'
import { Route as AppCampaignsIdRouteImport } from './routes/_app/campaigns.$id'
import { Route as AppMovementsIdRouteImport } from './routes/_app/movements.$id'
import { Route as AppOpportunitiesIdRouteImport } from './routes/_app/opportunities.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandRoute = AppBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesRoute = AppSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIdRoute = AppCampaignsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCampaignsRoute,
} as any)
const AppMovementsIdRoute = AppMovementsIdRouteImport.update({
  id: '/movements/$id',
  path: '/movements/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesIdRoute = AppOpportunitiesIdRouteImport.update({
  id: '/opportunities/$id',
  path: '/opportunities/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/analytics': typeof AppAnalyticsRoute
  '/approvals': typeof AppApprovalsRoute
  '/brand': typeof AppBrandRoute
  '/campaigns': typeof AppCampaignsRouteWithChildren
  '/map': typeof AppMapRoute
  '/settings': typeof AppSettingsRoute
  '/sources': typeof AppSourcesRoute
  '/campaigns/$id': typeof AppCampaignsIdRoute
  '/movements/$id': typeof AppMovementsIdRoute
  '/opportunities/$id': typeof AppOpportunitiesIdRoute
}
export interface FileRoutesByTo {
  '/analytics': typeof AppAnalyticsRoute
  '/approvals': typeof AppApprovalsRoute
  '/brand': typeof AppBrandRoute
  '/campaigns': typeof AppCampaignsRouteWithChildren
  '/map': typeof AppMapRoute
  '/settings': typeof AppSettingsRoute
  '/sources': typeof AppSourcesRoute
  '/': typeof AppIndexRoute
  '/campaigns/$id': typeof AppCampaignsIdRoute
  '/movements/$id': typeof AppMovementsIdRoute
  '/opportunities/$id': typeof AppOpportunitiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/brand': typeof AppBrandRoute
  '/_app/campaigns': typeof AppCampaignsRouteWithChildren
  '/_app/map': typeof AppMapRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sources': typeof AppSourcesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/campaigns/$id': typeof AppCampaignsIdRoute
  '/_app/movements/$id': typeof AppMovementsIdRoute
  '/_app/opportunities/$id': typeof AppOpportunitiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/approvals'
    | '/brand'
    | '/campaigns'
    | '/map'
    | '/settings'
    | '/sources'
    | '/campaigns/$id'
    | '/movements/$id'
    | '/opportunities/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analytics'
    | '/approvals'
    | '/brand'
    | '/campaigns'
    | '/map'
    | '/settings'
    | '/sources'
    | '/'
    | '/campaigns/$id'
    | '/movements/$id'
    | '/opportunities/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_app/analytics'
    | '/_app/approvals'
    | '/_app/brand'
    | '/_app/campaigns'
    | '/_app/map'
    | '/_app/settings'
    | '/_app/sources'
    | '/_app/'
    | '/_app/campaigns/$id'
    | '/_app/movements/$id'
    | '/_app/opportunities/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brand': {
      id: '/_app/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof AppBrandRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns': {
      id: '/_app/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/map': {
      id: '/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources': {
      id: '/_app/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AppSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/$id': {
      id: '/_app/campaigns/$id'
      path: '/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AppCampaignsIdRouteImport
      parentRoute: typeof AppCampaignsRoute
    }
    '/_app/movements/$id': {
      id: '/_app/movements/$id'
      path: '/movements/$id'
      fullPath: '/movements/$id'
      preLoaderRoute: typeof AppMovementsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opportunities/$id': {
      id: '/_app/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof AppOpportunitiesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppCampaignsRouteChildren {
  AppCampaignsIdRoute: typeof AppCampaignsIdRoute
}

const AppCampaignsRouteChildren: AppCampaignsRouteChildren = {
  AppCampaignsIdRoute: AppCampaignsIdRoute,
}

const AppCampaignsRouteWithChildren = AppCampaignsRoute._addFileChildren(
  AppCampaignsRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppBrandRoute: typeof AppBrandRoute
  AppCampaignsRoute: typeof AppCampaignsRouteWithChildren
  AppMapRoute: typeof AppMapRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSourcesRoute: typeof AppSourcesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMovementsIdRoute: typeof AppMovementsIdRoute
  AppOpportunitiesIdRoute: typeof AppOpportunitiesIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppBrandRoute: AppBrandRoute,
  AppCampaignsRoute: AppCampaignsRouteWithChildren,
  AppMapRoute: AppMapRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSourcesRoute: AppSourcesRoute,
  AppIndexRoute: AppIndexRoute,
  AppMovementsIdRoute: AppMovementsIdRoute,
  AppOpportunitiesIdRoute: AppOpportunitiesIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
